language: python
python:
- '3.6'
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then export CXX=g++-4.8; fi
  - wget https://github.com/rdfhdt/hdt-cpp/archive/v1.3.2.zip
  - unzip v1.3.2.zip
install:
  - pip install -r requirements.txt
  - pip install pytest
  - python setup.py install
script:
  - pytest
before_deploy:
  - rm -rf build/
deploy:
  skip_cleanup: true
  provider: pypi
  user: callidon
  password: $PYPI_PASSWD
  on:
    tags: true
